### ISSUE TITLE
large dataset causing "long vectors not supported yet" error

### ISSUE THREAD

**Issue by iiiir** [satijalab/seurat-data#11]
I am trying to install a single cell dataset with 70k+ cells, and getting the following errors:

```
> InstallData(c("mydata.SeuratData"))
Installing package into ‘~/apps/R/site-packages’
(as ‘lib’ is unspecified)
* installing *source* package mydata.SeuratData’ ...
** R
** data
*** moving datasets to lazyload DB
Error in lazyLoadDBinsertVariable(vars[i], from, datafile, ascii, compress,  :
  long vectors not supported yet: connections.c:5880
ERROR: lazydata failed for package mydata.SeuratData’
* removing ‘~/apps/R/site-packages/mydata.SeuratData’
Error in loadNamespace(name) :
  there is no package called mydata.SeuratData’
In addition: Warning message:
In install.packages(pkgs = pkgs, repos = getOption(x = "SeuratData.repo.use"),  :
  installation of package mydata.SeuratData’ had non-zero exit status
```
Anyone have suggestions on how to deal with "long vectors not supported yet" error while trying to install large dataset?

I am using R Version 3.5.3

Thanks,
Shuoguo

**Comment by mojaveazure** [comment]
Hi Shuoguo,

Unfortunately, we cannot provide much support for datasets not prepared by us. We are working on a guide that details how SeuratData works and how to extend it, but due to limited resource we will not be able to provide much more help than that. My guess is that this is due to limitations of R, not of SeuratData, but I can't help you more than that.
