### ISSUE TITLE
panc8 data has non-integers, not counts?

### ISSUE THREAD

**Issue by KristianHdL** [satijalab/seurat-data#8]
Hi, great work with this package. 

I wanted to use the SC-Transform pipeline for integrating the 8x pancreas-datasets, however the assay$RNA$counts slot contains non-integers, which gives warnings in SCTransform. Also I'm confused, as I would expect this slot to contain the raw counts which should be integers. (it's the same with the "old" 4-dataset pancreas file available from your dropbox for the old integration vignette...)
Both Celseq, Celseq2 and FluidigmC1 datasets contain non-integers.

**Comment by mojaveazure** [comment]
Hello,

Sorry for the delay. The original data are not counts, which is why you have non-integer numbers. For Seurat, the `counts` slot is simply the "raw data" slot (see [documentation for `Assay` objects](https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/Assay-class)). As for running SCTransform on non-integer data, I would recommend asking that question on the [Seurat](https://github.com/satijalab/seurat) or [sctransform](https://github.com/ChristophH/sctransform) GitHub repositories.

**Comment by jenniferngp** [comment]
Hello, I would also like to use the panc8 dataset. Is the assay$RNA@counts slot for this dataset TPM data?
